"""WHOT-ML Research Simulator package."""

from whot_ml.version import BASELINE_ENVIRONMENT, SIMULATOR_VERSION
from whot_ml.card import (
    Card,
    Shape,
    CardType,
    SpecialEffect,
    create_standard_deck,
    CANONICAL_DECK,
    CANONICAL_CARD_BY_ID,
    CANONICAL_CARD_BY_INDEX,
    TOTAL_DECK_SIZE,
    NUM_ORDINARY_CARDS,
    NUM_WHOT_CARDS,
)
from whot_ml.ruleset import (
    WHOTConfig,
    TurnDirection,
    StarterPolicy,
    StackingMode,
    FinalCardOnePolicy,
    MarketExhaustionPolicy,
    InitialCardPolicy,
    LastCardViolationPenalty,
    get_baseline_config,
)
from whot_ml.action import (
    Action,
    ActionType,
    TOTAL_ACTIONS,
    ACTION_INDEX_DRAW,
    ACTION_INDEX_DECLARE_LAST,
    action_to_index,
    index_to_action,
    make_play_card_action,
    make_play_whot_action,
    make_draw_action,
    make_declare_last_action,
)

__all__ = [
    "BASELINE_ENVIRONMENT",
    "SIMULATOR_VERSION",
    "Card",
    "Shape",
    "CardType",
    "SpecialEffect",
    "create_standard_deck",
    "CANONICAL_DECK",
    "CANONICAL_CARD_BY_ID",
    "CANONICAL_CARD_BY_INDEX",
    "TOTAL_DECK_SIZE",
    "NUM_ORDINARY_CARDS",
    "NUM_WHOT_CARDS",
    "WHOTConfig",
    "TurnDirection",
    "StarterPolicy",
    "StackingMode",
    "FinalCardOnePolicy",
    "MarketExhaustionPolicy",
    "InitialCardPolicy",
    "LastCardViolationPenalty",
    "get_baseline_config",
    "Action",
    "ActionType",
    "TOTAL_ACTIONS",
    "ACTION_INDEX_DRAW",
    "ACTION_INDEX_DECLARE_LAST",
    "action_to_index",
    "index_to_action",
    "make_play_card_action",
    "make_play_whot_action",
    "make_draw_action",
    "make_declare_last_action",
]
